name: Manual Deployment with Package, Version, and Env

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Select the package to deploy"
        required: true
        type: choice
        options:
          - java
          - daml
          - react-node
      version:
        description: "Select version to deploy"
        required: true
        type: choice
        options:
          - v1.0.0
          - v1.1.0
          - v2.0.0
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show Inputs
        run: |
          echo "Package: ${{ github.event.inputs.package }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Environment: ${{ github.event.inputs.environment }}"

      # Dev deployment block
      - name: Deploy to Dev
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: |
          echo "🚀 Deploying ${{ github.event.inputs.package }} version ${{ github.event.inputs.version }} to DEV server..."

      # Test deployment block
      - name: Deploy to Test
        if: ${{ github.event.inputs.environment == 'test' }}
        run: |
          echo "🚀 Deploying ${{ github.event.inputs.package }} version ${{ github.event.inputs.version }} to TEST server..."

      # Prod deployment block
      - name: Deploy to Prod
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: |
          echo "🚀 Deploying ${{ github.event.inputs.package }} version ${{ github.event.inputs.version }} to PROD server..."
