name: Manual Deployment with Multiple Packages and Versions

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Select the package to deploy"
        required: true
        type: choice
        options:
          - node
          - react
          - daml
      version:
        description: "Select version to deploy"
        required: true
        type: choice
        options:
          # Node versions
          - node-v1.0.0
          - node-v1.1.0
          - node-v2.0.0
          # React versions
          - react-v1.0.0
          - react-v1.1.0
          - react-v2.0.0
          # DAML versions
          - daml-v1.0.0
          - daml-v1.1.0
          - daml-v2.0.0
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show Inputs
        run: |
          echo "Package: ${{ github.event.inputs.package }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Environment: ${{ github.event.inputs.environment }}"

      # Node deployment block
      - name: Deploy Node
        if: ${{ github.event.inputs.package == 'node' && startsWith(github.event.inputs.version, 'node-') }}
        run: |
          echo "🚀 Deploying NODE app version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"

      # React deployment block
      - name: Deploy React
        if: ${{ github.event.inputs.package == 'react' && startsWith(github.event.inputs.version, 'react-') }}
        run: |
          echo "🚀 Deploying REACT app version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"

      # DAML deployment block
      - name: Deploy DAML
        if: ${{ github.event.inputs.package == 'daml' && startsWith(github.event.inputs.version, 'daml-') }}
        run: |
          echo "🚀 Deploying DAML app version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"
